### ISSUE TITLE
Integrate with an existing express server

### ISSUE THREAD

**Issue by mirkods** [indutny/bud-backend#1]
Hi,

I saw your module is using express to generate the server, so I would integrate it with my existing express server. 

```
var app = bud.createServer(conf);

app.configure(function () {  
    app.set('port', process.env.PORT || 8080);
    app.use(express.cookieParser());
    app.use(express.session({}));
    app.use()
    ... and other configuration
});

https.createServer(credentials, bud).listen(port)
```

Why the middleware chain is completely ignored during the requests?

**Comment by indutny** [comment]
Hi!

I have another solution for you: 582840b

Now `require('bud-backend').sni()` (and `.ocsp()`) will return middleware function, which you could use in your express server.

Hope this helps!

**Comment by mirkods** [comment]
Hi Fedor,
I have seen that in [this line](https://github.com/indutny/bud-backend/blob/master/lib/bud-backend/sni.js#L7) you used the SNI functionality only for the GET requests, why? 
What is options.sni.url?

Regards

**Comment by indutny** [comment]
@mirkods yep, only GET. bud only does GET SNI requests.

`options` is the first argument of `sni` function: https://github.com/indutny/bud-backend/blob/master/lib/bud-backend/sni.js#L3 . Same as `conf` here: https://github.com/indutny/bud-backend/blob/master/bin/bud-backend.js#L11

**Comment by mirkods** [comment]
Do you think there will be problems if the router is in listening with all http methods?

for example : 

``` javascript
router.all('*', function (req, res, next) {})
```

**Comment by indutny** [comment]
I don't think that there will be problems. But why do you need this?

**Comment by mirkods** [comment]
I need this to establish ssl connection based on different domains for REST API service.

**Comment by indutny** [comment]
You don't need all methods. `bud-backend` is just a configuration server for bud, not your website's backend.

**Comment by mirkods** [comment]
I'm using this as middleware on my front proxy to accept multiple domains on my platform. So i need all http methods to cover all the api requests. Any advice about it?

**Comment by indutny** [comment]
Wait, do you realize that this should not be exposed to public? This SNI request handler replies with a cert and **private key**. I doubt that you may want to run this as a middleware on your public server.

**Comment by mirkods** [comment]
Yes i know, but I have changed the response calling the next() in place of res.json

**Comment by indutny** [comment]
@mirkods sorry, but I don't think that I understand what you need. bud-backend is supposed to talk only to **bud**, and **bud** is using only **GET** method for SNI.

**Comment by mirkods** [comment]
Ok make sense! I have used the native SNI callback in node 0.12 version https.

Can I go off-topic? Do you know how can I reuse the tls session on multiple https requests?
I saw the resumeSession and newSession events on tls server but seems that they aren't emitted.

Thanks
