### ISSUE TITLE
Separate out lib/bud-backend/ocsp.js?

### ISSUE THREAD

**Issue by mikemaccana** [indutny/bud-backend#2]
The code here seems pretty generic, and right now there's no `ocsp` module (or any other OCSP response handler) on npm. Just a suggestion.

**Comment by indutny** [comment]
Started some preliminary work here: https://github.com/indutny/ocsp

**Comment by indutny** [comment]
Guess it is fixed now. Please let me know if it works for you!

**Comment by mikemaccana** [comment]
Awesome and thank you! 🗿
